# Generated by Django 3.2.6 on 2025-03-13 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_add_default_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lots_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
